---
molecule:
  # directory in CWD to place all temp files, etc.
  molecule_dir: .molecule

  # where temporary state will be stored (lives under molecule_dir)
  state_file: state

  # name of temporary vagrantfile created during runs (lives under molecule_dir)
  vagrantfile_file: vagrantfile

  # directories to ignore when doing trailing whitespace checks on files during verify command
  ignore_paths:
    - .git
    - .vagrant
    - .molecule

  # directory to look for goss tests
  goss_dir: tests/goss
  goss_playbook: verifier.yml

  # directory containing group_vars to use with ansible
  group_vars: ../tests/group_vars

# ansible related config
ansible:
  playbook: tests/playbook.yml

dependency:
  name: galaxy
  requirements_file: tests/requirements.yml

# configuration options for the internal call to vagrant
vagrant:
  raw_config_args:
    - "landrush.enabled = true"
    - "landrush.tld = ''"
    - "landrush.guest_redirect_dns = false"
  # molecule's --platform option will look for these names
  platforms:
    - name: Debian9
      box: debian/stretch64
    - name: Debian8
      box: debian/jessie64

  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 512
        cpus: 1

  instances:
    - name: agent01
      ansible_groups:
        - consul_agent
      interfaces:
        - network_name: private_network
          type: dhcp
          auto_config: true

    - name: server01
      ansible_groups:
        - consul_server
      interfaces:
        - network_name: private_network
          type: dhcp
          auto_config: true

    - name: server02
      ansible_groups:
        - consul_server
      interfaces:
        - network_name: private_network
          type: dhcp
          auto_config: true

    - name: server03
      ansible_groups:
        - consul_server
      interfaces:
        - network_name: private_network
          type: dhcp
          auto_config: true

docker:
  network:
    - name: consul-network
      driver: bridge

  containers:
    - name: agent01
      hostname: agent01
      ansible_groups:
        - consul_agent
      image: geerlingguy/docker-debian9-ansible
      image_version: latest
      privileged: True
      cap_add:
        - SYS_ADMIN
      volume_mounts:
        - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
      command: '/lib/systemd/systemd'
      network_mode: consul-network

    - name: server01
      hostname: server01
      ansible_groups:
        - consul_server
      image: geerlingguy/docker-debian9-ansible
      image_version: latest
      privileged: True
      cap_add:
        - SYS_ADMIN
      volume_mounts:
        - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
      command: '/lib/systemd/systemd'
      network_mode: consul-network

    - name: server02
      hostname: server02
      ansible_groups:
        - consul_server
      image: geerlingguy/docker-debian9-ansible
      image_version: latest
      privileged: True
      cap_add:
        - SYS_ADMIN
      volume_mounts:
        - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
      command: '/lib/systemd/systemd'
      network_mode: consul-network

    - name: server03
      hostname: server03
      ansible_groups:
        - consul_server
      image: geerlingguy/docker-debian9-ansible
      image_version: latest
      privileged: True
      cap_add:
        - SYS_ADMIN
      volume_mounts:
        - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
      command: '/lib/systemd/systemd'
      network_mode: consul-network

verifier:
  name: goss
