---
galaxy_info:
  company: Idealista S.A.U.
  author: Idealista S.A.U.
  description: Consul
  min_ansible_version: 2.9.0.0
  license: Apache 2.0
  platforms:
    - name: Debian
      versions:
        - stretch
        - buster
